<Project Sdk="Microsoft.NET.Sdk">
    <PropertyGroup>
        <TargetFramework>net10.0</TargetFramework>
        <LangVersion>latest</LangVersion>
        <TreatWarningsAsErrors>true</TreatWarningsAsErrors>
        <Nullable>enable</Nullable>
        <AvaloniaUseCompiledBindingsByDefault>true</AvaloniaUseCompiledBindingsByDefault>
    </PropertyGroup>
    <ItemGroup>
        <PackageReference Include="Material.Avalonia"/>
        <ProjectReference Include="..\Westermo.GraphX.Controls.Avalonia\Westermo.GraphX.Controls.Avalonia.csproj"/>
    </ItemGroup>

    <PropertyGroup>
        <AssemblyTitle>Westermo GraphX Material Theme</AssemblyTitle>
        <Description>Material Design theme for Westermo GraphX Avalonia controls</Description>
    </PropertyGroup>

</Project>
